#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/core.sh"

_create_file() {
    echo "$1" > "$dotrs"
    chmod +x "$dotrs"
}

_create_dotrs_fallback() {
    mkdir -p "$(dirname "$dotrs")" || true
    local content="$(echo "Stub"; echo; echo "Usage:"; echo "    dotrs")"
    _create_file "$content" "$dotrs"
    _create_file "$content" "${DOTFILES}/target/release/dotrs"
    _create_file "$content" "${DOTFILES}/rust/target/release/dotrs"
}

dotrs="${DOTFILES}/target/dotrs"
[ -f $dotrs ] || _create_dotrs_fallback

dot sh scripting test "${DOCPARS_HOME}/tests"
dot self test file '^bash \- help'